# Generated by Django 4.1.7 on 2023-04-18 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
